### ISSUE TITLE
KeyError: 'previous_output' in run_video.py when using RTS

### ISSUE THREAD

**Issue by moooises** [visionml/pytracking#372]
Hello,
Trying to run RTS with the run_video.py script I encounter the KeyError: 'previous_output'.
I will leave the full log below, but probably the problem is the same as in the issue https://github.com/visionml/pytracking/issues/217 .

```
Traceback (most recent call last):
  File "run_video.py", line 38, in <module>
    main()
  File "run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/content/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 352, in run_video
    out = tracker.track(frame)
  File "/content/pytracking/pytracking/../pytracking/evaluation/multi_object_wrapper.py", line 152, in track
    out = self.trackers[obj_id].track(image, info)
  File "/content/pytracking/pytracking/../pytracking/tracker/rts/rts.py", line 189, in track
    prev_seg_prob_im = info['previous_output']['segmentation_raw'][self.object_id]
KeyError: 'previous_output
```

**Comment by xjtuwh** [comment]
+1

**Comment by xjtuwh** [comment]
参考pytracking/pytracking/evaluation/tracker.py中的run_vot2020

**Comment by moooises** [comment]
Hello,
I checked the method _run_vot2020_ and was able to get the _run_video_ method working with **RTS** tracker.
You just need to prepare the **info** dictionary the same way as the _run_vot2020_ method  and then add it as a parameter to _tracker.track(frame, info)_.

I leave here the tracker.py [code ](https://drive.google.com/file/d/15ti1cIyLgoNaTcr0YAY5ntXssJEpv_2O/view?usp=sharing)in case someone needs it.
Maybe some lines are unnecessary, but it works for now.

**Comment by mattpfr** [comment]
@moooises thank you for the answer! Indeed, the code for `run_video.py` was not adapted to segmentation approaches.
I am adjusting the scripts so you can run RTS (and LWL) on videos and webcam! That should cover as well #217 

I will push the changes as soon as they are reviewed and tested.

**Comment by mattpfr** [comment]
@moooises @xjtuwh I pushed a fix for the `run_video.py` please pull the latest version and let me know if everything works fine for you.

**Comment by moooises** [comment]
Sorry for the late response.

At the moment I'm working using Google Colab, so I needed to comment every line that makes a windows pop up and set the pause value to **False**. I also added a VideoWriter class to see the output result.

I tried the Keep_Track tracker and it seems to work fine. I couldn't make it work with multiple object, but I 'm still not sure if _keep_track.py_ is prepared for it, but for the rest it seems fine.

**Comment by moooises** [comment]
I modified a bit the part where the tracker is initialized following the function is this issue https://github.com/visionml/pytracking/issues/159#issuecomment-644591656 and I could make the Keep_Track tracker work with multiple objects.

```
optional_boxes=[(670, 366, 50, 50),(513, 255, 71, 65)]

if optional_box is not None:
    assert isinstance(optional_box, (list, tuple))
    assert len(optional_box) == 4, "valid box's format is [x,y,w,h]"

    boxes=OrderedDict()
    ids=[]

    for i,box in enumerate(optional_boxes):
        i+=1

        boxes.update({i:box})
        ids.append(i)
        output_boxes[i]=[box,]
        sequence_object_ids.append(i)

    out = tracker.initialize(frame, {'init_bbox': boxes,
                            'init_object_ids': ids,
                            'object_ids': ids,
                            'sequence_object_ids': ids})

    prev_output = OrderedDict(out)
```

**Comment by moooises** [comment]
I have also noted some weird things when tracking multiple objects. Sometimes I don't get the same results when using the same inputs. I'm going to investigate more and maybe I will open another issue.

**Comment by 2006pmach** [comment]
If you use KeepTrack this is expected since it is non-deterministic. SuperDiMP uses random augmentations to form the initial training frames stored in the memory. Thus, the results can vary from run to run.

**Comment by moooises** [comment]
Yes, I was using KeepTrack. That explains a lot, thanks for your answer.
After the weekend I will try RTS. If I found something I will report it.

**Comment by mattpfr** [comment]
@moooises ok thanks, I let you try RTS a bit more and then will close this ticket!

**Comment by moooises** [comment]
I have tried RTS tracking multiple objects and seems to work fine. I get the same results every time I use the same inputs.

**Comment by mattpfr** [comment]
Alright, great then!

**Comment by li-xinxiang** [comment]
I had an error loading the rts50.pth model while testing the RTS, as follows:
A load persistent id instruction was encountered,
but no persistent_load function was specified.
How can I fix it
